name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4
      - name: 打包项目
        run: |
          npm install
          npm run build
      - name: 部署
        uses: JamesIves/github-pages-deloy-action@v4
        with:
          branch: 'gh-pages'
          folder: 'dist'
